on:
  schedule:
    - cron: '0 9 * * 1,4' # Runs at 9:00 AM UTC every Monday and Thursday
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # ✅ Upgrade to Node.js 20

      # Step 3: Install Supabase Client
      - name: Install Supabase Client
        run: npm install @supabase/supabase-js --force

      # Step 4: Ping Supabase
      - name: Ping Supabase
        env:
          SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.NEXT_SERVICE_ROLE_KEY }}
        run: |
          node -e "
          (async () => {
            try {
              const { createClient } = require('@supabase/supabase-js');
              const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);

              const { data, error } = await supabase
                .from('quiz_questions')
                .select('*')
                .limit(1);

              if (error) throw error;

              console.log('Ping successful:', data);
            } catch (err) {
              console.error('Error pinging Supabase:', err);
              process.exit(1);
            }
          })();
          "
